name: Atualizar cards do perfil

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Gerar cards do perfil
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: Juskk59
          BRANCH_NAME: main
          UTC_OFFSET: -3
          AUTO_PUSH: true
